import type { ItineraryItem, QuoteDocument, PresetActivity } from '../types/itinerary';

// 图一：原始客户发来的 18 天行程单
export const figure1Itinerary: ItineraryItem[] = [
  { id: '1', day: 'Day 1', date: '12月18日', route: '皇后镇接机 1215 + 游览', activity: '' },
  { id: '2', day: 'Day 2', date: '12月19日', route: '皇后镇', activity: 'TSS + 晚餐' },
  { id: '3', day: 'Day 3', date: '12月20日', route: '皇后镇', activity: '米尔布鲁克' },
  { id: '4', day: 'Day 4', date: '12月21日', route: '皇后镇', activity: '杰克斯角' },
  { id: '5', day: 'Day 5', date: '12月22日', route: '皇后镇 - 格林诺奇 - 皇后镇', activity: '天空缆车' },
  { id: '6', day: 'Day 6', date: '12月23日', route: '皇后镇 - 蒂阿瑙', activity: '萤火虫洞' },
  { id: '7', day: 'Day 7', date: '12月24日', route: '蒂阿瑙 - 峡湾 - 但尼丁', activity: '' },
  { id: '8', day: 'Day 8', date: '12月25日', route: '但尼丁 - 大圆石 - 奥马鲁', activity: '看小企鹅迁徙' },
  { id: '9', day: 'Day 9', date: '12月26日', route: '奥马鲁 - 库克山', activity: '' },
  { id: '10', day: 'Day 10', date: '12月27日', route: '库克山 - 蒂卡波', activity: '塔斯曼冰河探险' },
  { id: '11', day: 'Day 11', date: '12月28日', route: '蒂卡波 - 基督城', activity: '' },
  { id: '12', day: 'Day 12', date: '12月29日', route: '基督城 - 阿卡罗阿 - 基督城', activity: '龙虾船（包船）/ 出海看海豚' },
  { id: '13', day: 'Day 13', date: '12月30日', route: '基督城 / 奥克兰', activity: '' },
  { id: '14', day: 'Day 14', date: '12月31日', route: '奥克兰 - 霍比特 - 罗托鲁阿', activity: '霍比特村游览' },
  { id: '15', day: 'Day 15', date: '1月1日', route: '罗托鲁阿 - 陶波湖 - 罗托鲁阿', activity: '毛利文化村 / 陶波湖游览' },
  { id: '16', day: 'Day 16', date: '1月2日', route: '罗托鲁阿 - 奥克兰', activity: '爱歌顿皇家牧场' },
  { id: '17', day: 'Day 17', date: '1月3日', route: '奥克兰 打球', activity: '' },
  { id: '18', day: 'Day 18', date: '1月4日', route: '奥克兰送机', activity: '' },
];

// 用户指定的真实标准模板：26.12.18 南北岛18天.xlsx
export const standard18DaysQuoteDoc: QuoteDocument = {
  title: '26.12.18 南北岛18天',
  psNote: 'PS： 26春节：2.16-26 附加费',
  includeCostBreakdown: true,
  updatedAt: '2026-09-07',
  itinerary: [
    {
      id: 'day-1',
      day: 'Day 1',
      date: '12月18日',
      route: '皇后镇接机 1420 + 游览',
      activity: '',
      southIslandCar: 800,
      otherSurcharge: 600,
      southGuideMeal: 50,
    },
    {
      id: 'day-2',
      day: 'Day 2',
      date: '12月19日',
      route: '皇后镇 - 格林诺奇 - 皇后镇',
      activity: 'TSS + 晚餐 NZD 199/人',
      southIslandCar: 850,
      otherSurcharge: 200,
      southGuideMeal: 75,
    },
    {
      id: 'day-3',
      day: 'Day 3',
      date: '12月20日',
      route: '皇后镇 - 瓦纳卡 - 皇后镇',
      activity: '天空缆车 NZD 69/人',
      southIslandCar: 850,
      otherSurcharge: 200,
      southGuideMeal: 75,
    },
    {
      id: 'day-4',
      day: 'Day 4',
      date: '12月21日',
      route: '皇后镇 - 峡湾 - 蒂阿瑙',
      activity: '峡湾游轮 + 游轮自助',
      southIslandCar: 850,
      southGuideMeal: 75,
    },
    {
      id: 'day-5',
      day: 'Day 5',
      date: '12月22日',
      route: '蒂阿瑙 - 水果小镇 - 但尼丁',
      activity: '',
      southIslandCar: 850,
      southGuideMeal: 75,
      guideAccommodation: 200,
    },
    {
      id: 'day-6',
      day: 'Day 6',
      date: '12月23日',
      route: '但尼丁 - 大圆石 - 奥马鲁',
      activity: '看小企鹅迁徙 NZD 67/人',
      southIslandCar: 850,
      southGuideMeal: 75,
      guideAccommodation: 200,
    },
    {
      id: 'day-7',
      day: 'Day 7',
      date: '12月24日',
      route: '奥马鲁 - 库克山 - 蒂卡波湖',
      activity: '',
      southIslandCar: 850,
      holidaySurcharge: 175,
      southGuideMeal: 75,
    },
    {
      id: 'day-8',
      day: 'Day 8',
      date: '12月25日',
      route: '库克山 - 蒂卡波',
      activity: '塔斯曼冰河探险 NZD 219/人',
      southIslandCar: 850,
      holidaySurcharge: 175,
      southGuideMeal: 75,
      guideAccommodation: 300,
    },
    {
      id: 'day-9',
      day: 'Day 9',
      date: '12月26日',
      route: '蒂卡波 - 基督城',
      activity: '',
      southIslandCar: 850,
      holidaySurcharge: 175,
      southGuideMeal: 75,
    },
    {
      id: 'day-10',
      day: 'Day 10',
      date: '12月27日',
      route: '基督城 - 阿卡罗阿 - 基督城',
      activity: '龙虾船 NZD 3500(包船）\n出海看海豚 NZD 125/人',
      southIslandCar: 850,
      otherSurcharge: 200,
      southGuideMeal: 50,
    },
    {
      id: 'day-11',
      day: 'Day 11',
      date: '12月28日',
      route: '基督城 / 奥克兰 1605 // 1730',
      activity: '南极中心 NZD 74/人',
      northIslandCar: 750,
      southIslandCar: 850,
      northGuideMeal: 40,
      southGuideMeal: 25,
    },
    {
      id: 'day-12',
      day: 'Day 12',
      date: '12月29日',
      route: '奥克兰 - 霍比特 - 罗托鲁阿',
      activity: '霍比特村游览 NZD 120/人',
      northIslandCar: 750,
      northGuideMeal: 40,
      guideAccommodation: 180,
    },
    {
      id: 'day-13',
      day: 'Day 13',
      date: '12月30日',
      route: '罗托鲁阿',
      activity: '毛利文化村 NZD 142/人\n爱歌顿皇家牧场 NZD 61/人',
      northIslandCar: 750,
      northGuideMeal: 60,
      guideAccommodation: 180,
    },
    {
      id: 'day-14',
      day: 'Day 14',
      date: '12月31日',
      route: '罗托鲁阿 - 陶波湖 - 罗托鲁阿',
      activity: '陶波湖游览',
      northIslandCar: 750,
      holidaySurcharge: 175,
      northGuideMeal: 60,
      guideAccommodation: 180,
    },
    {
      id: 'day-15',
      day: 'Day 15',
      date: '1月1日',
      route: '罗托鲁阿 - 萤火虫洞 - 奥克兰',
      activity: '萤火虫洞 NZD 81/人',
      northIslandCar: 750,
      holidaySurcharge: 175,
      otherSurcharge: 150,
      northGuideMeal: 60,
    },
    {
      id: 'day-16',
      day: 'Day 16',
      date: '1月2日',
      route: '奥克兰 市区游览',
      activity: '',
      northIslandCar: 750,
      holidaySurcharge: 175,
      otherSurcharge: 1500,
      northGuideMeal: 40,
    },
    {
      id: 'day-17',
      day: 'Day 17',
      date: '1月3日',
      route: '奥克兰送机 1045',
      activity: '',
      northGuideMeal: 20,
    },
  ],
  vehicleQuote: {
    totalPrice: 19985,
    currency: 'NZD',
    vehicleModel: '7 座 Alphard',
    inclusions: [
      '车：16座奔驰 + 拖斗，燃油，机场卡，车辆保险',
      '司兼导服务，司导工资；司导住宿（未含库克山司导住宿），餐补',
    ],
    exclusions: [
      '小费：NZD 6每人每天（请现金结算给导游，南北岛分开计算）',
      '不含行程以外的路程费，',
      '不含旅游保险（建议自行购买）',
    ],
    notes: [
      '工作时间：全天不超过10小时，超时部分按照 NZD150/小时（含GST）计算',
      '此报价有效期为2周，报价以最终航班时间为准，目前并未座任何预留',
    ],
  },
  activityQuote: {
    adultPrice: 2080,
    currency: 'NZD',
    includedActivities: [
      '凯库拉观鲸',
      'Alpacas farm',
      '直升机飞峡湾 + 峡湾游轮+ 午餐（餐盒）',
      '山顶缆车',
      'TSS 游湖',
      '霍比特村游览',
      'Wai O Tapu 地热公园门票',
      '怀托摩萤火虫洞',
    ],
    customActivityText: '凯库拉观鲸，Alpacas farm， 直升机飞峡湾 + 峡湾游轮+ 午餐（餐盒）；山顶缆车；TSS 游湖；霍比特村游览，Wai O Tapu 地热公园门票；怀托摩萤火虫洞',
  },
};

// 预置常用新西兰活动与门票参考库（NZD）
export const presetActivities: PresetActivity[] = [
  { id: 'act-1', name: 'TSS 厄恩斯劳号蒸汽船 + 瓦尔特峰农场晚餐', location: '皇后镇', adultPrice: 199, childPrice: 95, description: '百年蒸汽船体验及高地农庄BBQ自助晚餐' },
  { id: 'act-2', name: '天空缆车 Skyline Gondola', location: '皇后镇', adultPrice: 69, childPrice: 34, description: '俯瞰皇后镇全景与瓦卡蒂普湖' },
  { id: 'act-3', name: '天空缆车 + 山顶自助晚餐', location: '皇后镇', adultPrice: 135, childPrice: 75, description: '全景餐厅精美自助' },
  { id: 'act-4', name: '萤火虫洞 Glowworm Caves', location: '罗托鲁阿/怀托摩', adultPrice: 81, childPrice: 40, description: '地下乘船观赏奇幻萤火虫' },
  { id: 'act-5', name: '峡湾游轮 + 游轮自助', location: '峡湾', adultPrice: 165, childPrice: 85, description: '世界第八大奇迹峡湾深度巡游' },
  { id: 'act-6', name: '直升机飞峡湾 + 峡湾游轮 + 午餐（餐盒）', location: '峡湾', adultPrice: 980, childPrice: 650, description: '高空俯瞰南阿尔卑斯雪山与峡湾' },
  { id: 'act-7', name: '看小企鹅迁徙', location: '奥马鲁', adultPrice: 67, childPrice: 35, description: '近距离观赏世界上最小的小蓝企鹅' },
  { id: 'act-8', name: '塔斯曼冰河探险', location: '库克山', adultPrice: 219, childPrice: 110, description: '乘专用冲锋舟探访冰川湖浮冰' },
  { id: 'act-9', name: '出海看海豚', location: '基督城/阿卡罗阿', adultPrice: 125, childPrice: 65, description: '寻访珍稀赫氏海豚' },
  { id: 'act-10', name: '南极中心', location: '基督城', adultPrice: 74, childPrice: 45, description: '企鹅喂食与极地风暴体验' },
  { id: 'act-11', name: '霍比特村游览', location: '奥克兰/玛塔玛塔', adultPrice: 120, childPrice: 60, description: '电影魔戒/指环王取景地深度导览' },
  { id: 'act-12', name: '毛利文化村', location: '罗托鲁阿', adultPrice: 142, childPrice: 70, description: '波胡图间歇泉与毛利歌舞' },
  { id: 'act-13', name: '爱歌顿皇家牧场', location: '罗托鲁阿', adultPrice: 61, childPrice: 35, description: '喂羊驼、剪羊毛表演' },
  { id: 'act-14', name: 'Wai O Tapu 地热公园门票', location: '罗托鲁阿', adultPrice: 45, childPrice: 20, description: '香槟池与彩色地热泉' },
  { id: 'act-15', name: '凯库拉观鲸', location: '凯库拉', adultPrice: 165, childPrice: 80, description: '观赏巨大的抹香鲸和海豚' },
];

export const presetVehicles = [
  { id: 'v1', name: '7 座 Alphard', baseDayPrice: 850, capacity: '4人及行李', desc: '头等舱保姆车，尊贵出行体验' },
  { id: 'v2', name: '16座奔驰 + 拖斗', baseDayPrice: 1300, capacity: '8-12人及行李', desc: '豪华商务首选，带独立行李拖斗' },
  { id: 'v3', name: '12座丰田海狮 (Hiace) + 拖斗', baseDayPrice: 1050, capacity: '6-9人及行李', desc: '经典舒适商务中巴' },
  { id: 'v4', name: '8座奔驰 V-Class', baseDayPrice: 950, capacity: '4-5人及行李', desc: '高端商务多功能车' },
  { id: 'v5', name: '20-25座考斯特中巴', baseDayPrice: 1550, capacity: '14-18人及行李', desc: '适合大家庭或中型商务考察团队' },
];
